// Mirrors PermissionCodes from IndiaHRMS.Domain.Constants exactly
export const PERMISSIONS = {
  EMPLOYEE: {
    VIEW: 'EMPLOYEE.VIEW',
    CREATE: 'EMPLOYEE.CREATE',
    EDIT: 'EMPLOYEE.EDIT',
    DELETE: 'EMPLOYEE.DELETE',
    EXPORT: 'EMPLOYEE.EXPORT',
  },
  PAYROLL: {
    VIEW: 'PAYROLL.VIEW',
    PROCESS: 'PAYROLL.PROCESS',
    APPROVE: 'PAYROLL.APPROVE',
    EXPORT: 'PAYROLL.EXPORT',
    GENERATE: 'PAYROLL.GENERATE',
    CONFIGURE: 'PAYROLL.CONFIGURE',
  },
  LEAVE: {
    VIEW: 'LEAVE.VIEW',
    CREATE: 'LEAVE.CREATE',
    EDIT: 'LEAVE.EDIT',
    APPROVE: 'LEAVE.APPROVE',
    REJECT: 'LEAVE.REJECT',
    EXPORT: 'LEAVE.EXPORT',
    CONFIGURE: 'LEAVE.CONFIGURE',
  },
  ATTENDANCE: {
    VIEW: 'ATTENDANCE.VIEW',
    CREATE: 'ATTENDANCE.CREATE',
    EDIT: 'ATTENDANCE.EDIT',
    APPROVE: 'ATTENDANCE.APPROVE',
    EXPORT: 'ATTENDANCE.EXPORT',
    IMPORT: 'ATTENDANCE.IMPORT',
  },
  RECRUITMENT: {
    VIEW: 'RECRUITMENT.VIEW',
    CREATE: 'RECRUITMENT.CREATE',
    EDIT: 'RECRUITMENT.EDIT',
    DELETE: 'RECRUITMENT.DELETE',
    APPROVE: 'RECRUITMENT.APPROVE',
    EXPORT: 'RECRUITMENT.EXPORT',
  },
  PERFORMANCE: {
    VIEW: 'PERFORMANCE.VIEW',
    CREATE: 'PERFORMANCE.CREATE',
    EDIT: 'PERFORMANCE.EDIT',
    APPROVE: 'PERFORMANCE.APPROVE',
    EXPORT: 'PERFORMANCE.EXPORT',
  },
  COMPANY_SETUP: {
    VIEW: 'COMPANY_SETUP.VIEW',
    CREATE: 'COMPANY_SETUP.CREATE',
    EDIT: 'COMPANY_SETUP.EDIT',
    DELETE: 'COMPANY_SETUP.DELETE',
  },
  USER_MANAGEMENT: {
    VIEW: 'USER_MGMT.VIEW',
    CREATE: 'USER_MGMT.CREATE',
    EDIT: 'USER_MGMT.EDIT',
    DELETE: 'USER_MGMT.DELETE',
    ASSIGN: 'USER_MGMT.ASSIGN',
  },
  AUDIT: {
    VIEW: 'AUDIT.VIEW',
    EXPORT: 'AUDIT.EXPORT',
  },
  REPORTS: {
    VIEW: 'REPORTS.VIEW',
    EXPORT: 'REPORTS.EXPORT',
    GENERATE: 'REPORTS.GENERATE',
    CUSTOM: 'REPORTS.CUSTOM',
  },
  COMPLIANCE: {
    VIEW: 'COMPLIANCE.VIEW',
    MANAGE: 'COMPLIANCE.MANAGE',
    EXPORT: 'COMPLIANCE.EXPORT',
  },
}

// Role codes mirroring RoleCodes in backend
export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  IT_ADMIN: 'IT_ADMIN',
  HR_ADMIN: 'HR_ADMIN',
  HR_MANAGER: 'HR_MANAGER',
  RECRUITMENT_MANAGER: 'RECRUITMENT_MGR',
  PAYROLL_ADMIN: 'PAYROLL_ADMIN',
  FINANCE_VIEWER: 'FINANCE_VIEWER',
  DEPARTMENT_MANAGER: 'DEPT_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
  AUDITOR: 'AUDITOR',
}
